version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
  worker:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - redis
  beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - redis
  web:
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
