# Generated by Django 4.2.24 on 2025-09-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Opłacone"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reminder_sent",
            field=models.BooleanField(
                default=False, verbose_name="Wysłano przypomnienie"
            ),
        ),
    ]
